// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error)
	CreateAuctionImage(ctx context.Context, arg CreateAuctionImageParams) (AuctionImage, error)
	CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error)
	CreateRegisterAuction(ctx context.Context, arg CreateRegisterAuctionParams) (RegisterAuction, error)
	CreateRegisterAuctionImage(ctx context.Context, arg CreateRegisterAuctionImageParams) (RegisterAuctionImage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserImage(ctx context.Context, arg CreateUserImageParams) (UserImage, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error)
	GetAuctionById(ctx context.Context, id int32) (Auction, error)
	GetByCode(ctx context.Context, code string) (Auction, error)
	GetByEmail(ctx context.Context, email string) (User, error)
	GetById(ctx context.Context, id int32) (User, error)
	GetByIdCard(ctx context.Context, idCard string) (User, error)
	GetByUserName(ctx context.Context, userName string) (User, error)
	GetByUserNameActive(ctx context.Context, userName string) (User, error)
	GetListAuction(ctx context.Context, arg GetListAuctionParams) ([]Auction, error)
	GetListRegisterAuction(ctx context.Context, arg GetListRegisterAuctionParams) ([]User, error)
	GetListRegisterAuctionByUserId(ctx context.Context, arg GetListRegisterAuctionByUserIdParams) ([]GetListRegisterAuctionByUserIdRow, error)
	GetListUser(ctx context.Context, arg GetListUserParams) ([]User, error)
	GetMaxBid(ctx context.Context, auctionID int32) (interface{}, error)
	GetRegisterAuctionById(ctx context.Context, id int32) (RegisterAuction, error)
	GetRegisterAuctionByUserId(ctx context.Context, arg GetRegisterAuctionByUserIdParams) (GetRegisterAuctionByUserIdRow, error)
	GetRoleByUserId(ctx context.Context, userID int32) (int32, error)
	GetTotalAuction(ctx context.Context, code string) (int64, error)
	GetTotalRegisterAuction(ctx context.Context, auctionID int32) (int64, error)
	GetTotalUser(ctx context.Context, userName string) (int64, error)
	ListAuctionImage(ctx context.Context, auctionID int32) ([]string, error)
	ListImage(ctx context.Context, userID int32) ([]string, error)
	ListRegisterAuctionImage(ctx context.Context, registerAuctionID int32) ([]RegisterAuctionImage, error)
	ListRole(ctx context.Context) ([]Role, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) (User, error)
	UpdateStatusAuction(ctx context.Context, arg UpdateStatusAuctionParams) (Auction, error)
	UpdateStatusRegisterAuction(ctx context.Context, arg UpdateStatusRegisterAuctionParams) (RegisterAuction, error)
}

var _ Querier = (*Queries)(nil)
