package constant

const (
	PRODUCTION = "production"

	AUCTION_STATUS_INIT     = 0
	AUCTION_STATUS_VERIFIED = 1

	REGISTER_AUCTION_STATUS_INIT     = 0
	REGISTER_AUCTION_STATUS_VERIFIED = 1

	USER_STATUS_INIT     = 0
	USER_STATUS_VERIFIED = 1
	USER_STATUS_LOCKED   = -1

	ROLE_ID_ADMIN        = 1
	ROLE_ID_OPERATOR     = 2
	ROLE_ID_USER         = 3
	ROLE_ID_ORGANIZATION = 4
)
